### ISSUE TITLE
Enter Publisher Information

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#1]
Publisher information for the journals (and potentially books) needs to be entered into the Administrative interface in the translation-aware sections.  

NOTE: If only in one language is to be used, the English needs to be copied to the other configurations--Neil can do that or set up a program to automate this in the future.

To create a publisher entry, go into Admin, English section, down to the Publishers, then click on the publisher to edit, and enter data into the two fields.

https://user-images.githubusercontent.com/4837554/114030664-9f24fa00-9848-11eb-8baf-b039b568258b.mp4

**Comment by nrshapiro** [comment]
Just a reminder, while testing the latest version of the client, I noted that this data has still not been entered for 95% of the journals.  I know lots of other things are going on, but this is part of the user interface too.

**Comment by SophieMBennett** [comment]
@nrshapiro I'm currently working through adding the Journal info to the English setting.

**Comment by davidtuckett** [comment]
Neil,
Yes. Sophie has it on her list. Many thanks.
Hope you had a good break.
David

**Comment by SophieMBennett** [comment]
@nrshapiro Update / I've added the publisher info for all journals in the English Admin setting. 

nb. ISSN and frequency - I have omitted this data for now, because not many journals were displaying it (on PEP) and I need to locate these details. I've started, but I want to add them simultaneously to maintain consistency and may not be able to do it before the upcoming release. Once they are included, we can work out how to best duplicate the info to the other langage settings as per your note above.

eg. for format
ISSN: 2632-0134
e-ISSN: 2632-0142
Frequency: Biannual

**Comment by davidtuckett** [comment]
Thank you Neil. In medium time I have in mind doing much more with this - including possibly linking to or including interestig infromtion from journal editors or subsctiptin information. All for discussion. It coud be a signifucant source of income and influence. We will start with IJP.

**Comment by SophieMBennett** [comment]
https://github.com/Psychoanalytic-Electronic-Publishing/Support/issues/59

Linking this here for reference.
