### ISSUE TITLE
Preview videos on the homepage - Latest and Topical

### ISSUE THREAD

**Issue by SophieMBennett** [Psychoanalytic-Electronic-Publishing/PEP-Web-Configuration#16]
@nrshapiro What is the process for updating the video previews on the homepage in the Admin setting. It would be good to be able to update these more regularly in sync with the newest video upload.

Currently, I can see the links but they refer to s3.amazonaws.com so I am unsure how to establish the correct link. e.g.
https://pep-web-video-previews.s3.amazonaws.com/peptopauthvs.001.0027a.preview.mp4

I was thinking it might be nice to update these for the release - we could perhaps add recent previews for Nancy McWilliams (PEPTOPAUTH) and one of the recent Lockdown Dreams animations?

Is it the case that the more you add, that they revolve, as with the daily graphic / editors picks?

![Video previews on Homepage](https://user-images.githubusercontent.com/83074920/150155340-29064b4f-f8ee-44f6-899b-b40498c91bcc.PNG)

**Comment by nrshapiro** [comment]
@SophieMBennett 

Anything you add to Dropbox PEP for All\Inventory\AWSProd Video Previews is automatically copied to S3. So you can change that address 

Currently, this is done via my computer.  Eventually, we will have Gavant automate on AWS the updates...but for now it's done by a program called Goodsync, used to move PEP-Web inventory materials around since we don't have a one-place-fits-all-supplier needs location.  I have about 20 folders being synchronized between S3, FTP, and Dropbox.

You can queue them.  It's not clear to me whether it works.  When we divided up into phases, the spec pushed this to Rev.2.  We never actually finished Rev.1 before the plug was pulled on Gavant.  You could try queuing them and see if they change.  I've never noticed because the video frame is buried on the left and rarely is in view.

[Core] Video Preview - This card shall show a feature preview video linked from PEP's Facebook page.  
[Core] PEP shall be able to select the video to be previewed via [AdminMode].  
[Rev.2] PEP shall be able to queue up videos by date via [AdminMode].

**Comment by SophieMBennett** [comment]
@nrshapiro Thanks for clarifying. I've added some recent videos on Stage under those tabs and will see if they rotate over a certain time period.

**Comment by nrshapiro** [comment]
See https://github.com/Psychoanalytic-Electronic-Publishing/PEP-Web-User-Interface/issues/640
